config/routes.rb
Whatshoulditweet::Application.routes.draw do
  resources :users, :only => [:index, :show] do
    collection do
      get :lookup
    end
  end

  root :to => 'users#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def lookup
    username = (params[:username] || '').strip.delete('@')
    redirect_to user_path(username)
  end

  def index
  end

  def show
    @username = params[:id]
    @tweets   = Twitter.user_timeline(@username,
      :count       => 200,
      :include_rts => false,
      :trim_user   => true
    )

    generator = TwoChainz::Generator.new
    shortest  = 140
    longest   = 0

    @tweets.each do |tweet|
      text = tweet.text
      generator.hear(text)

      # Record counts
      length   = text.length
      shortest = length if length < shortest
      longest  = length if length > longest
    end

    @potential_tweet = generator.spit(
      :max_chars => longest,
      :min_chars => shortest
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whatshoulditweet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>What should I tweet?</h1>
<p>How about something similar to all the shit you've tweeted before.</p>

<h2>what's yo name</h2>

<%= form_tag(lookup_users_path, :method => :get) do -%>
  @<input name="username" type="text">

  <button type="submit">is my name on Twitter</button>
<% end -%>

app/views/users/show.html.erb
<h1>wassup <%= @username %>.</h1>
<p>Here's something you'd prolly tweet:</p>

<div class="potential-tweet"><%= @potential_tweet %></div>

<%= form_tag(lookup_users_path, :method => :get) do -%>
  <button type="submit">get another tweet for</button>
  @<input name="username" type="text" value="<%= @username %>">
<% end -%>

<h2>Some of your recent tweets that were used</h2>

<ul class="past-tweets">
  <% @tweets.each do |tweet| %>
    <li>
      <%= tweet.text %>
    </li>
  <% end %>
</ul>